-- To show grants on a table.
SHOW GRANT ON PROD_DB.DWH.TABLE_NAME;
SHOW GRANTS ON DATABASE.SCHEMA.TABLE_NAME;


-- To look for big test tables.
SET DAY_TO_LOOKBACK = (SELECT DATE(DATEADD(DAY, -10, CURRENT_TIMESTAMP)));
SELECT TABLE_NAME AS TABLE_NAME, 
	SUM(BYTES)/1024/1024/1024/1024 AS SIZE_IN_TB
	FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_SCHEMA = 'DWH'
		AND TABLE_NAME ILIKE ANY('%backup%', '%bkp%', '%test%', '%_1')
		AND LAST_ALTERED < $DAY_TO_LOOKBACK
	GROUP BY 1 HAVING SIZE_IN_TB > 0.1 ORDER BY 2 DESC


-- To create a view with `COPY GRANTS` 
-- When the COPY GRANTS parameter is specified in a CREATE TABLE statement, 
-- The create operation copies all privileges, except OWNERSHIP, from the source table to the new table.

CREATE OR REPLACE VIEW SCHEMA.FACT_VIEW_NAME COPY GRANTS (
	COLUMN_NAME1,
	COLUMN_NAME2,
	COLUMN_NAME3

) AS 
SELECT COLUMN_NAME1, COLUMN_NAME2, SOME_CALCULATION AS COLUMN_NAME3 FROM TABLE SCHEMA.TABLE_NAME;


CREATE SEQUENCE SEQ_LOAD_JOB_PARAMS_TABLE_JOB_ID START WITH 1 INCREMENT BY 1;

CREATE FILE FORMAT PDWH.APP_LOGS TYPE = CSV RECORD_DELIMETER='0x0a'
 FIELD_DELIMETER='NONE'
 SKIP_HEADER=0
 DATE_FORMAT='AUTO'
 TIME_FORMAT='AUTO'
 TIMESTAMP_FORMAT='AUTO'
 BINARY_FORMAT='HEX'
 ESCAPE='NONE'
 ESCAPE_UNENCLOSED_FIELD='NONE'
 TRIM_SPACE=False
 FIELD_OPTIONALLY_ENCLOSED_BY='NONE'
 NULL_IF=('')
 COMPRESSION='GZIP'
 ERROR_ON_COLUMN_COUNT_MISMATCH=True
 VALIDATE_UTF8=True
 EMPTY_FIELD_AS_NULL=True
 SKIP_BYTE_ORDER_MARK=True
 ENCODING='UTF8'
;


CREATE FILE FORMAT PDWH.JSON TYPE = JSON
 COMPRESSION='AUTO'
 ENABLE_OCTAL=False
 ALLOW_DUPLICATE=False
 STRIP_OUTER_ARRAY=False
 STRIP_NULL_VALUES=False
 IGNORE_UTF8_ERRORS=False
 SKIP_BYTE_ORDER_MARK=True
;

CREATE FILE FORMAT PDWH.PARQUET TYPE = PARQUET BINARY_AS_TEXT=True
 SNAPPY_COMPRESSION=True
;



