-- To show grants on a table 
SHOW GRANT ON PROD_DB.DWH.TABLE_NAME;
SHOW GRANTS ON DATABASE.SCHEMA.TABLE_NAME;



SET DAY_TO_LOOKBACK = (SELECT DATE(DATEADD(DAY, -10, CURRENT_TIMESTAMP)));
SELECT TABLE_NAME AS TABLE_NAME, 
	SUM(BYTES)/1024/1024/1024/1024 AS SIZE_IN_TB
	FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_SCHEMA = 'DWH'
		AND TABLE_NAME ILIKE ANY('%backup%', '%bkp%', '%test%', '%_1')
		AND LAST_ALTERED < $DAY_TO_LOOKBACK
	GROUP BY 1 HAVING SIZE_IN_TB > 0.1 ORDER BY 2 DESC



